projects/fww/Controllers/MyAdsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using fww.Models;
using System.Data.Entity;

namespace fww.Controllers
{
    public class MyAdsController : Controller
    {
        public ActionResult Index()
        {
            using (CommonContext db = new CommonContext())
            {
                var model = (from items in db.Ads where items.OwnerID == User.Identity.Name select items).ToList();
                model.Reverse();
                ViewBag.IsUnread = IsUnread();
                return View(model);
            }
        }

        public ActionResult New()
        {
            ViewBag.IsUnread = IsUnread();
            return View();
        }

        [HttpPost]
        public ActionResult New(Ad advert)
        {
            using (CommonContext db = new CommonContext()) 
            {
                advert.Date = DateTime.Now;
                advert.Engaged = 0;
                advert.Views = 0;
                advert.Theme = advert.Theme;
                advert.OwnerID = User.Identity.Name;
                advert.Country = advert.Country;

                db.Ads.Add(advert);
                db.SaveChanges();
            }            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            ViewBag.IsUnread = IsUnread();
            if (id == null)
            {
                return HttpNotFound();
            }
            using (CommonContext db = new CommonContext())
            {
                Ad advert = db.Ads.Find(id);
                if (advert != null)
                {
                    return View(advert);
                }

                return HttpNotFound();
            }
        }
        [HttpPost]
        public ActionResult Edit(Ad advert)
        {
            using (CommonContext db = new CommonContext())
            {
                Ad ad = db.Ads.Find(advert.Id);
                ad.Title = advert.Title;
                ad.Text = advert.Text;
                ad.Keywords = advert.Keywords;
                ad.Theme = advert.Theme;
                ad.Date = DateTime.Now;
                ad.Country = advert.Country;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        
        public ActionResult Delete(int? id)
        {
            using (CommonContext db = new CommonContext())
            {
                Ad ad = db.Ads.Find(id);
                db.Ads.Remove(ad);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public bool IsUnread()
        {
            bool IsUnread = false;
            using (CommonContext ctx = new CommonContext())
            {
                List<MessageRel> mr = (from items in ctx.MessageRels
                                       where (items.Receiver == User.Identity.Name && items.Unread == true)
                                       select items).ToList<MessageRel>();
                IsUnread = (mr.Count == 0) ? false : true;
            }
            return IsUnread;
        }

	}
}

projects/fww/Views/MyAds/Edit.cshtml
@{
    ViewBag.Title = "Редагування";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string[] themes = File.ReadAllLines(Server.MapPath("~/App_Data/Themes.txt"));
    string[] cities = File.ReadAllLines(Server.MapPath("~/App_Data/Countries.txt"));
}
@model fww.Models.Ad



<main class="my-ads">
    <form method="post" action="/MyAds/Edit">
        <label for="title">Title</label>
        <textarea maxlength="100" name="Title" id="title"
                  placeholder="shortly describe your idea here..">@Model.Title</textarea>

        <label for="text">Text</label>
        <textarea maxlength="800" name="Text" id="text" placeholder="type addition info here..">@Model.Text</textarea>

        <label for="theme">Theme</label>
        <select name="Theme" id="theme">
            @foreach (string item in themes)
            {
                if (Model.Theme == item)
                {
                    <option selected value="@item">@item</option> }
                else
                {
                    <option value="@item">@item</option> }
            }
        </select>

        <label for="location">Country</label>
        <select name="Location" id="location">
            @foreach (string item in cities)
            {
                if (Model.Country == item)
                {
                    <option selected value="@item">@item</option> }
                else
                {
                    <option value="@item">@item</option> }
            }
        </select>

        <label for="keywords">Keywords</label>
        <input name="Keywords" id="keywords" type="text" value="@Model.Keywords" />

        <input name="Id" type="hidden" value="@Model.Id" />

        <a href="/MyAds/Delete/@Model.Id">Delete this ad</a>
        <input name="editButton" type="submit" value="Safe Changes" />

    </form>
</main>
    


@*<label for="file">Зображення</label>
    <label for="file" class="upload-label">Обрати</label>
    <input id="file" type="file" name="file" class="upload" />*@

projects/fww/Views/MyAds/Index.cshtml
@{
    ViewBag.Title = "My ads";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using fww.Models;
@model List<Ad>


<main class="my-ads">
    <div class="row">
        @Html.ActionLink("Create new ad", "New", "MyAds")
    </div>
    @if (Model.Count != 0)
    {
        foreach (var m in Model)
        {
            if (m != null)
            {
                <div class="record" onclick="window.location.href = '/Ads/No/@m.Id'">
                    <div class="record-main-line">
                        <p>@m.Title we are going to help ukranians to beat theur president</p>
                    </div>
                <div class="record-info">
                    <div class="textual">
                        <p>Тема: @m.Theme</p>
                        <p>Місце: @m.Country</p>
                    </div>
                    <div class="visual">
                        <p>@m.Date</p>
                        @*<p class="edit-icon"><a href="#"><img src="@Url.Content("~/Content/Images/edit.png")" /></a></p>
                        <p class="subs-icon"><img src="@Url.Content("~/Content/Images/subs.png")" /> 93</p>
                        <p class="stars-icon"><img src="@Url.Content("~/Content/Images/star.png")" /> 81</p>
                        <a href="/MyAds/Edit/@m.Id" class="edit-pencil">Редагувати</a>*@
                    </div>
                </div>
            </div>



                @*<div class="record" onclick="window.location.href = '/Ads/No/@m.Id'">
                    <div class="recordTitle">@m.Title <a href="/MyAds/Edit/@m.Id" class="edit-pencil">Редагувати</a></div>
                    <div class="recordText">@m.Text</div>
                    <div class="record-info-bar">
                        <div>Підписано: @m.Engaged</div>
                        <div>Тема: @m.Theme</div>
                        <div>Місце: @m.Country</div>
                        <div class="recordTime">@m.Date.ToString("dd/MM/yyyy")</div>
                    </div>
                </div>*@
            }
        }
    }
    else { <div> У Вас поки-що немає своїх оголошень. </div> }

</main>


        

    

projects/fww/Views/MyAds/New.cshtml
@model fww.Models.Ad

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "New Ad";
    string[] themes = File.ReadAllLines(Server.MapPath("~/App_Data/Themes.txt"));
    string[] countries = File.ReadAllLines(Server.MapPath("~/App_Data/Countries.txt"));
    string[] regions = File.ReadAllLines(Server.MapPath("~/App_Data/Regions.txt"));

    string[] ukraine = File.ReadAllLines(Server.MapPath("~/App_Data/Ukraine.txt"));
    string[] usa = File.ReadAllLines(Server.MapPath("~/App_Data/USA.txt"));
    string[] russia = File.ReadAllLines(Server.MapPath("~/App_Data/Russia.txt"));
    
}


<main class="my-ads">
    <form method="post" action="/MyAds/New">
        <label for="title">Title</label>
        <textarea maxlength="100" name="Title" id="title" 
                  placeholder="shortly describe your idea here.."></textarea>

        <label for="text">Text</label>
        <textarea maxlength="800" name="Text" id="text" placeholder="type addition info here.." ></textarea>

        <label for="theme">Theme</label>
        <select name="Theme" id="theme">
            @foreach (string item in themes) { <option value="@item">@item</option> }
        </select>
                
        <label for="location">Country</label>
        <select name="Location">
            @foreach (string item in countries) { <option value="@item">@item</option> }
        </select>

        <label for="location">Region</label>
        <select name="Location" class="select-new">
            @foreach (string item in regions) { <option value="@item">@item</option> }
        </select>

        <label for="keywords">Tags</label>
        <input name="Keywords" id="keywords" type="text" placeholder="(max 5)" />
            
        <input name="newButton" type="submit" value="Publish" />
    </form>
</main>


@*<div class="div-new">
        <label for="text">Text</label>
        <textarea name="Text" id="text" placeholder="type here.." class="message-input-new"></textarea>
    </div>*@

@*<div>
        <label for="location">Region</label>
        <select name="Location" class="select-new">
            @foreach (string item in regions)
            {
                <option value="@item">@item</option>
            }
        </select>
    </div>*@